#!/bin/bash

echo "🔧 Activating Resume Processing Pipeline workflow..."
echo ""
echo "📋 Manual activation steps:"
echo "1. Go to n8n at http://localhost:5678"
echo "2. Click 'Workflows' in the left sidebar"
echo "3. Find 'Resume Processing Pipeline' workflow"
echo "4. Click on the workflow to open it"
echo "5. Toggle the 'Active' switch in the top-right corner"
echo "6. Save the workflow"
echo ""
echo "✅ Once activated, the webhook will be available at:"
echo "   http://localhost:5678/webhook/resume-upload-webhook"
echo ""
echo "🧪 Test the webhook with:"
echo "   curl -X POST http://localhost:5678/webhook/resume-upload-webhook \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"test\": \"data\"}'"
